on:
  push:
    branches:
      - master
  pull_request: null

name: Code Analysis
jobs:
  matrix:
    strategy:
      fail-fast: false
      matrix:
        actions:
          - name: PHPStan
            run: composer phpstan --ansi

          - name: Psalm
            run: composer psalm --ansi

          - name: Ecs
            run: composer check-cs --ansi

          - name: UnitTest
            run: |
              composer test --ansi
              ./vendor/bin/php-coveralls --coverage_clover=build/logs/clover.xml -v

    name: ${{ matrix.actions.name }}
    env:
      COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: pcov
          tools: composer:v2

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - run: ${{ matrix.actions.run }}
