on:
  push:
    branches:
      - master
  pull_request: null

name: Code Analysis
jobs:
  matrix:
    strategy:
      fail-fast: false
      matrix:
        actions:
          - name: PHPStan
            run: composer phpstan --ansi

          - name: Psalm
            run: composer psalm --ansi

          - name: Ecs
            run: composer check-cs --ansi

          - name: UnitTest
            run: |
              composer test --ansi
              ./vendor/bin/php-coveralls --coverage_clover=build/logs/clover.xml -v

          - name: Coveralls
            uses: coverallsapp/github-action@master

    name: ${{ matrix.actions.name }}
    env:
      COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: pcov
          tools: composer:v2
      - run: composer install --no-progress --prefer-dist --ansi
      - run: ${{ matrix.actions.run }}
